# yml 버전 지정
version: '3'

# 볼륨 세팅, 컨테이너가 종료되어도 데이터가 유실되지 않도록 호스트의 일부 영역을 할당
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/hyowon/42Seoul/11_Inception/inception/mariadb # /home/hyowchoi/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/hyowon/42Seoul/11_Inception/inception/wordpress # /home/hyowchoi/data/wordpress
      o: bind

# 컨테이너 실행
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb

    # 컨테이너로 실행할 대상 이미지 설정
    image: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mariadb # mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - ./.env
    
    # 컨테이너가 종료되어도 자동으로 재실행
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx

    # mariadb 컨테이너가 실행되어야만 nginx 컨테이너가 실행될 수 있도록 설정, 리스닝 상태까지 도달했는지는 확인하지 않음, 시작 유무만 확인
    depends_on:
      - mariadb
    
    # 노출시킬 포트, <host port>:<container port> 형태로 지정.
    # host port를 생략 : 임의의 포트가 할당, host port를 지정 : 해당 포트로 접근 가능
    # -로 여러 개의 포트를 지정해줄 수 있음
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress

    # 연결된 타 컨테이너와의 통신만 가능, 호스트 OS에서의 접근은 불가
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - ./.env
    restart: always

networks:
  inception_network:
    driver: bridge